export const GET_FOLDERS = 'GET_FOLDERS'
export const SET_FOLDERS = 'SET_FOLDERS'
export const SET_FILES = 'SET_FILES'
export const ADD_FOLDER = 'ADD_FOLDER'
export const ADD_FILE = 'ADD_FILE'
export const DELETE_FOLDER = 'DELETE_FOLDER'
export const DELETE_FILE = 'DELETE_FILE'
